plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_23
    targetCompatibility = JavaVersion.VERSION_23
}

group = 'toby.spring.kt'
version = '1.0-SNAPSHOT'

ext {
    volName = 'Vol1-31'
    targetPath = volName + '/Ch4/4.2.4/'
    libsPath = volName + '/lib/'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: libsPath, include: ['*.jar'])

    implementation 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation "org.junit.jupiter:junit-jupiter-api:5.14.2"
    implementation "com.mysql:mysql-connector-j:9.5.0"

    implementation "org.junit.jupiter:junit-jupiter-engine:5.14.2"
    implementation "org.junit.platform:junit-platform-commons:1.14.2"
    implementation "org.junit.platform:junit-platform-engine:1.14.2"
    implementation "org.junit.platform:junit-platform-launcher:1.14.2"

    testImplementation 'org.slf4j:slf4j-api:2.0.17'
    testImplementation 'org.slf4j:slf4j-log4j12:2.0.17'

    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"

    testImplementation "org.testcontainers:mysql:1.21.4"
}

sourceSets {
    main {
        kotlin {
            srcDirs = [targetPath + 'src/main/kotlin']
        }
        resources {
            srcDirs = [targetPath, targetPath + 'src/main/resources']
        }
    }

    test {
        kotlin {
            srcDirs = [targetPath + 'src/test/kotlin']
        }
        resources {
            srcDirs = [targetPath + 'src/test/resources']
        }
    }
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE // 최신 파일 유지, 이전파일 덮어쓰기 처리
}

test {
    testClassesDirs += sourceSets.main.output.classesDirs

    classpath += sourceSets.main.runtimeClasspath

    filter {
        includeTestsMatching "*Test"
    }
}