plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_23
    targetCompatibility = JavaVersion.VERSION_23
}

group = 'toby.spring.kt'
version = '0.1-SNAPSHOT'

ext {
    volName = 'Vol1-31'
    targetPath = volName + '/Ch6/6.3.2/'
    libsPath = volName + '/legacy/'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: libsPath, include: ['*.jar'])
    
    //  maven repo에 존재하지 않아 수동 등록
    //  implementation 'net.sourceforge.cglib:com.springsource.net.sf.cglib:2.2.0'
    //  implementation 'commons-logging:commons-logging:1.1.1'
    //  implementation 'javax.mail:com.springsource.javax.mail:1.4.0'
    //  implementation 'javax.activation:com.springsource.javax.activation:1.1.0'
    //  implementation 'org.springframework:org.springframework.transaction:3.1.2.RELEASE'

    implementation 'org.assertj:assertj-core:3.18.0'
    implementation 'org.springframework:spring-asm:3.1.2.RELEASE'
    implementation 'org.springframework:spring-beans:3.1.2.RELEASE'
    implementation 'org.springframework:spring-context:3.1.2.RELEASE'
    implementation 'org.springframework:spring-context-support:3.1.2.RELEASE'
    implementation 'org.springframework:spring-core:3.1.2.RELEASE'
    implementation 'org.springframework:spring-expression:3.1.2.RELEASE'
    implementation 'org.springframework:spring-jdbc:3.1.2.RELEASE'
    implementation 'org.springframework:spring-test:3.1.2.RELEASE'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation "com.mysql:mysql-connector-j:9.5.0"

    implementation 'junit:junit:4.13.1'
    implementation "org.junit.jupiter:junit-jupiter-api:5.14.2"
    implementation "org.junit.jupiter:junit-jupiter-engine:5.14.2"
    implementation "org.junit.platform:junit-platform-commons:1.14.2"
    implementation "org.junit.platform:junit-platform-engine:1.14.2"
    implementation "org.junit.platform:junit-platform-launcher:1.14.2"

    implementation 'org.mockito.kotlin:mockito-kotlin:5.2.1'
    implementation 'org.mockito:mockito-core:5.11.0'
    implementation 'org.mockito:mockito-inline:5.2.0'
    implementation 'net.bytebuddy:byte-buddy:1.15.0'
    implementation 'net.bytebuddy:byte-buddy-agent:1.15.0'

    testImplementation 'org.slf4j:slf4j-api:2.0.17'
    testImplementation 'org.slf4j:slf4j-log4j12:2.0.17'
    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
    testImplementation "org.testcontainers:mysql:1.21.4"
}

sourceSets {
    main {
        kotlin {
            srcDirs = [targetPath + 'src/main/kotlin']
        }
        resources {
            srcDirs = [targetPath + 'src/main/resources']
        }
    }

/*    test {
        kotlin {
            srcDirs = [targetPath + 'src/test/kotlin']
        }
        resources {
            srcDirs = [targetPath + 'src/test/resources']
        }
    }*/
}

/*tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE // 최신 파일 유지, 이전파일 덮어쓰기 처리
}*/

/*test {
    testClassesDirs += sourceSets.main.output.classesDirs

    classpath += sourceSets.main.runtimeClasspath

    filter {
        includeTestsMatching "*Test"
    }
}*/
